import {
  siHtml5,
  siCss,
  siJavascript,
  siTypescript,
  siReact,
  siNextdotjs,
  siExpo,
  siTailwindcss,
  siShadcnui,
  siNodedotjs,
  siExpress,
  siNestjs,
  siPostgresql,
  siMysql,
  siDrizzle,
  siPrisma,
  siJsonwebtokens,
  siDocker,
  siGit,
  siGithub,
  siRailway,
  siVercel,
  siPostman,
  siDotenv,
  siC,
} from "simple-icons"

export const iconMap = {
  html5: siHtml5,
  css: siCss,
  javascript: siJavascript,
  typescript: siTypescript,
  react: siReact,
  nextdotjs: siNextdotjs,
  expo: siExpo,
  tailwindcss: siTailwindcss,
  shadcnui: siShadcnui,
  nodedotjs: siNodedotjs,
  express: siExpress,
  nestjs: siNestjs,
  postgresql: siPostgresql,
  mysql: siMysql,
  drizzle: siDrizzle,
  prisma: siPrisma,
  jsonwebtokens: siJsonwebtokens,
  docker: siDocker,
  git: siGit,
  github: siGithub,
  railway: siRailway,
  vercel: siVercel,
  postman: siPostman,
  dotenv: siDotenv,
  c: siC,
} as const

export type IconSlug = keyof typeof iconMap
